package com.digitalid.api.audit;

public enum AuditAction {
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET,
    PROFILE_UPDATE,
    TOKEN_REFRESH,
    EMAIL_SENT,
    EMAIL_FAILED,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    SERVICE_CONNECTED,
    SERVICE_DISCONNECTED,
    CREDENTIAL_VERIFY_STARTED,
    IDENTITY_VERIFY_SUBMITTED,
    ACCOUNT_DELETE
}
