package com.digitalid.api.audit;

public enum AuditAction {
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET,
    PROFILE_UPDATE,
    TOKEN_REFRESH,
    EMAIL_SENT,
    EMAIL_FAILED,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    SERVICE_CONNECTED,
    SERVICE_DISCONNECTED,
    CREDENTIAL_VERIFY_STARTED,
    IDENTITY_VERIFY_SUBMITTED,
    ACCOUNT_DELETE,
    // Admin actions
    ADMIN_USER_CREATED,
    ADMIN_USER_DELETED,
    ADMIN_USER_STATUS_CHANGED,
    ADMIN_USER_ROLE_CHANGED,
    ADMIN_INSTITUTION_CREATED,
    ADMIN_INSTITUTION_DELETED,
    ADMIN_INSTITUTION_PERMISSIONS_CHANGED,
    ADMIN_VERIFICATION_REVIEWED,
    ADMIN_DOCUMENT_REVIEWED,
    // Third-party verification actions
    THIRD_PARTY_VERIFY_SUCCESS,
    THIRD_PARTY_VERIFY_FAILED,
    CREDENTIAL_VERIFY_SUCCESS,
    CREDENTIAL_VERIFY_FAILED,
    IDENTITY_VERIFY_APPROVED,
    IDENTITY_VERIFY_REJECTED
}
